---
.travis.yml:
secure: "pGNud07xWsBKkhSD5wIg3QEhT4Rta3NMVaygTPPgrVIEh0DuCOKlaWpETvGaXAK1jvoYp3nUa/vObAYLyt0YytYD8JWPNXHmtBpSBBir9tSoYwd0xncwQLZtUuNKFwc1eIY95AmbZTeESL6qMKE6CLw5ACVpSjlfSWdCtpbjalGei7P/wGG0uUWWU7WTXV/NH24PPRKT8FBFTQo2hd5VIj075Vcu0aMOgE+cfpPwFUBBsy2RBYSrFnFBOgqR7a8wSr7igMXOfoOQFwZaHMifFVOncfsJaOJ6p5WHFOZRGIL3k4AzeP2gRCtucRE5K2eg7UEdqMJttuxHwYhKwj1KhSsemjAuGmanr7eK5ioeK+U24A9g1bXe/VhveHnJJTt153975CXVi7ccP9M8B9SyjToBwAYzGFLTpQI29mAKMtw7lVtrwgrz+aHTst1kEiPLxutDRQgcm0K/0d8+HlxAy9yQzLHKR7cK2CNXpUkNu3IgkuDYh+FysxSjhhB2f5CjnUoXTDVuvpiu7Yw7I2YFIL3nmtYlHs0ffT29k3q8ao5WzZ1v+cMo2jk/kJV1tEX/gl1Uls01AWlGDbAaKsDmV+UIT2Do+GaZY7vZuONkW2AO6nxDUpawQJ6Lde4q+EbnTH2ihw9qBN2FeQTGlfHfl9eg7BajTFcOZRbL7ZQ8484="
Gemfile:
  optional:
    ':test':
      - gem: 'toml'
